# Generated by Django 6.0.4 on 2026-04-11 15:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=50)),
                ('detail', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='jobs.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jobs_audit_log',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='AutoApplyPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allowed', models.BooleanField(default=False)),
                ('daily_limit', models.IntegerField(default=10)),
                ('require_approval', models.BooleanField(default=True)),
                ('granted_at', models.DateTimeField(blank=True, null=True)),
                ('terms_accepted', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='auto_apply_permission', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jobs_auto_apply_permission',
            },
        ),
        migrations.CreateModel(
            name='ApplicationQueue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('match_score', models.FloatField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('submitted', 'Submitted'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('cover_letter', models.TextField(blank=True)),
                ('queued_at', models.DateTimeField(auto_now_add=True)),
                ('applied_at', models.DateTimeField(blank=True, null=True)),
                ('failure_reason', models.TextField(blank=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_queue', to='jobs.job')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_queue', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'jobs_application_queue',
                'ordering': ['-queued_at'],
                'unique_together': {('user', 'job')},
            },
        ),
    ]
