# Generated by Django 5.2.12 on 2026-03-23 02:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ResourceCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("icon", models.CharField(max_length=50)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Resource Categories",
                "db_table": "resource_hub_category",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("description", models.TextField()),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("course", "Course"),
                            ("article", "Article"),
                            ("tutorial", "Tutorial"),
                            ("video", "Video"),
                            ("book", "Book"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        max_length=20,
                    ),
                ),
                ("content", models.TextField(blank=True, null=True)),
                ("external_url", models.URLField(blank=True, null=True)),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="resource_thumbnails/"
                    ),
                ),
                ("author", models.CharField(blank=True, max_length=200, null=True)),
                ("duration_minutes", models.IntegerField(blank=True, null=True)),
                ("skills_covered", models.TextField(blank=True, null=True)),
                ("views_count", models.IntegerField(default=0)),
                ("likes_count", models.IntegerField(default=0)),
                ("featured", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resources",
                        to="resource_hub.resourcecategory",
                    ),
                ),
            ],
            options={
                "db_table": "resource_hub_resource",
                "ordering": ["-featured", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SkillPath",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField()),
                ("target_skill", models.CharField(max_length=100)),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        max_length=20,
                    ),
                ),
                ("estimated_hours", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "resources",
                    models.ManyToManyField(
                        related_name="skill_paths", to="resource_hub.resource"
                    ),
                ),
            ],
            options={
                "db_table": "resource_hub_skill_path",
            },
        ),
        migrations.CreateModel(
            name="UserResourceProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_completed", models.BooleanField(default=False)),
                ("is_liked", models.BooleanField(default=False)),
                ("progress_percentage", models.IntegerField(default=0)),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "resource",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_progress",
                        to="resource_hub.resource",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="resource_progress",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "resource_hub_user_progress",
                "unique_together": {("user", "resource")},
            },
        ),
    ]
