# Generated by Django 5.2.12 on 2026-03-23 01:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ForumCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("icon", models.CharField(blank=True, max_length=50, null=True)),
                ("color", models.CharField(default="primary", max_length=20)),
                ("order", models.IntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Forum Categories",
                "db_table": "forum_category",
                "ordering": ["order"],
            },
        ),
        migrations.CreateModel(
            name="ForumThread",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("content", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("closed", "Closed"),
                            ("pinned", "Pinned"),
                            ("locked", "Locked"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("views_count", models.IntegerField(default=0)),
                ("replies_count", models.IntegerField(default=0)),
                ("is_featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forum_threads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="threads",
                        to="forum.forumcategory",
                    ),
                ),
            ],
            options={
                "db_table": "forum_thread",
                "ordering": ["-is_featured", "-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ForumReply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("is_solution", models.BooleanField(default=False)),
                ("upvotes", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forum_replies",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "thread",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="forum.forumthread",
                    ),
                ),
            ],
            options={
                "db_table": "forum_reply",
                "ordering": ["-is_solution", "-upvotes", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="ForumUpvote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reply",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="upvoted_by",
                        to="forum.forumreply",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forum_upvotes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "forum_upvote",
            },
        ),
        migrations.CreateModel(
            name="UserBadge",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "badge_type",
                    models.CharField(
                        choices=[
                            ("contributor", "Contributor"),
                            ("expert", "Expert"),
                            ("helpful", "Helpful"),
                            ("active", "Active Member"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                ("icon", models.CharField(max_length=50)),
                ("earned_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forum_badges",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "forum_user_badge",
            },
        ),
        migrations.CreateModel(
            name="UserReputation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reputation_points", models.IntegerField(default=0)),
                ("threads_created", models.IntegerField(default=0)),
                ("helpful_replies", models.IntegerField(default=0)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="forum_reputation",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "forum_user_reputation",
            },
        ),
        migrations.AddIndex(
            model_name="forumthread",
            index=models.Index(
                fields=["category", "-created_at"],
                name="forum_threa_categor_f73386_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="forumthread",
            index=models.Index(fields=["status"], name="forum_threa_status_bc04d3_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="forumupvote",
            unique_together={("user", "reply")},
        ),
        migrations.AlterUniqueTogether(
            name="userbadge",
            unique_together={("user", "badge_type")},
        ),
    ]
