# Generated by Django 5.2.12 on 2026-03-23 01:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CVTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("template_file", models.FileField(upload_to="cv_templates/")),
                ("preview_image", models.ImageField(upload_to="cv_template_previews/")),
                ("category", models.CharField(max_length=50)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "cv_analyzer_cv_template",
            },
        ),
        migrations.CreateModel(
            name="CVAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cv_file", models.FileField(upload_to="cv_analysis/")),
                ("overall_score", models.IntegerField(default=0)),
                ("format_score", models.IntegerField(default=0)),
                ("content_score", models.IntegerField(default=0)),
                ("keyword_score", models.IntegerField(default=0)),
                ("readability_score", models.IntegerField(default=0)),
                ("format_feedback", models.TextField(blank=True, null=True)),
                ("content_feedback", models.TextField(blank=True, null=True)),
                ("keyword_feedback", models.TextField(blank=True, null=True)),
                ("readability_feedback", models.TextField(blank=True, null=True)),
                ("extracted_skills", models.TextField(blank=True, null=True)),
                ("extracted_experience", models.TextField(blank=True, null=True)),
                ("extracted_education", models.TextField(blank=True, null=True)),
                ("overall_feedback", models.TextField(blank=True, null=True)),
                ("recommendations", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_analyzed", models.BooleanField(default=False)),
                ("analysis_time_taken", models.FloatField(default=0)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cv_analyses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "cv_analyzer_cv_analysis",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CVFeedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "feedback_type",
                    models.CharField(
                        choices=[
                            ("spelling", "Spelling Error"),
                            ("grammar", "Grammar Error"),
                            ("format", "Format Issue"),
                            ("content", "Content Issue"),
                            ("suggestion", "Suggestion"),
                        ],
                        max_length=20,
                    ),
                ),
                ("section", models.CharField(max_length=100)),
                ("issue", models.TextField()),
                ("suggestion", models.TextField()),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("critical", "Critical"),
                            ("major", "Major"),
                            ("minor", "Minor"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedback_items",
                        to="cv_analyzer.cvanalysis",
                    ),
                ),
            ],
            options={
                "db_table": "cv_analyzer_cv_feedback",
                "ordering": ["severity"],
            },
        ),
        migrations.CreateModel(
            name="KeywordDatabase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("industry", models.CharField(max_length=100)),
                ("job_title", models.CharField(max_length=100)),
                ("keywords", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "cv_analyzer_keyword_database",
                "unique_together": {("industry", "job_title")},
            },
        ),
    ]
